name: Code quality check

on:
  pull_request:
    branches:
      - develop

jobs:
  check_code:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ['3.10', '3.11']

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort flake8-docstrings
            pip install black

        - name: Configure Linters
          run: echo "Configuring Linters" && cp setup.cfg $HOME/setup.cfg

        - name: Run linters
          run: |
            python -m flake8

        - name: Run code formatter (Black)
          run: black . --diff --color
